# Example of all possible appveyor.yml options
# http://www.appveyor.com/docs/appveyor-yml

# Not a .NET Project or Solution so prevent appveyor from complaining.  Were just utilizing it for automation.  Not
# Building .net application
build: off

test_script:
  - ps: .\Invoke-Build.ps1

- provider: Slack
  incoming_webhook:
    secure: https://hooks.slack.com/services/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